Upgrade library for ssh connection to :nerves_ssh
```
==> nerves_ssh
Compiling 5 files (.ex)

== Compilation error in file lib/nerves_ssh/application.ex ==
** (RuntimeError) :nerves_ssh isn't configured, but :nerves_firmware_ssh is.

This is probably not right. If you recently upgraded to :nerves_ssh or
a library that uses it like :nerves_pack, you'll need to edit your config.exs
and rename references to :nerves_firmware_ssh to :nerves_ssh. See
https://hexdocs.pm/nerves_ssh/readme.html#configuration.

To use both :nerves_ssh and :nerves_firmware_ssh simultaneously, supply a
:nerves_ssh config to bypass this error.

    lib/nerves_ssh/application.ex:10: (module)
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :nerves_ssh, "mix compile" failed. You can recompile this dependency with "mix deps.compile nerves_ssh", update it with "mix deps.update nerves_ssh" or clean it with "mix deps.clean nerves_ssh"
```